print(123)
print('Tsinghua')
print("Haoge")
print("i'm good ennouge")
print('I\'m GOOD')
print('A'+'B')
print('A'+'666')
print('A'+str(666))
print('1+2')
print(int('1')+2)
print(float('1.2')+2)